language: node_js
node_js:
  - "14.16.1"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm install
script:
  - npm run lint
  - npm run build-aot
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
